// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqauvzruhcwavotytave.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxYXV2enJ1aGN3YXZvdHl0YXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODE4NDAsImV4cCI6MjA2NTI1Nzg0MH0.SsRt7zz1TH6feWYuKuRpj6uT3Ufe1ZIGQH5u7VbB5Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);