// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdeyqmidrynbsvdrrvvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZXlxbWlkcnluYnN2ZHJydnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzI3MjAsImV4cCI6MjA2NTMwODcyMH0.O7A85Ju4lvQw6sqEgcenn2nxfZ21Vrkhu0Di32jWUZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);